# Generated by Django 4.1.3 on 2022-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_add_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
