# Generated by Django 3.2.16 on 2022-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdone',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
